### PR TITLE
rpicamera: add text overlay with current time (#1288)

### LINKED ISSUE #1288: rpi camera stream: insert date and time in the video stream
### Discussed in https://github.com/aler9/rtsp-simple-server/discussions/1207

<div type='discussions-op-text'>

<sup>Originally posted by **vongillus** October 28, 2022</sup>
I just succeeded in configuring a rpi with its camera with both RTSP and HLS low latency. Thanks a lot for your work on this software!

I was wondering, is there any way to insert the date and time on the video? It will be a way to check that the video is not frozen. I mean in a more general way, to insert text on the video.
</div>

### PR DESCRIPTION
**Pull request by aler9**
Fixes #1288

### CODE REVIEW

**Comment by aler9** [comment]
@vongillus @gofaster @jarrah31 @filby112 @lejibxl @universe241981 if you have some time, help me test this feature by using the attached nightly release and let me know if it works and suits your needs.
[rtsp-simple-server_v0.21.6-17-g885a391_linux_arm64v8.tar.gz](https://github.com/aler9/rtsp-simple-server/files/11068873/rtsp-simple-server_v0.21.6-17-g885a391_linux_arm64v8.tar.gz)
[rtsp-simple-server_v0.21.6-17-g885a391_linux_armv6.tar.gz](https://github.com/aler9/rtsp-simple-server/files/11068876/rtsp-simple-server_v0.21.6-17-g885a391_linux_armv6.tar.gz)
[rtsp-simple-server_v0.21.6-17-g885a391_linux_armv7.tar.gz](https://github.com/aler9/rtsp-simple-server/files/11068880/rtsp-simple-server_v0.21.6-17-g885a391_linux_armv7.tar.gz)

**Comment by gofaster** [comment]
Thanks for adding this!  The `rtsp-simple-server_v0.21.6-17-g885a391_linux_armv7` nightly seems to be crashing for me.

```

2023/03/25 09:06:03 INF MediaMTX / rtsp-simple-server v0.21.6-17-g885a391
2023/03/25 09:06:03 DEB [path cam] created
2023/03/25 09:06:03 DEB path manager created
2023/03/25 09:06:03 INF [path cam] [rpicamera source] started
2023/03/25 09:06:03 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/03/25 09:06:03 INF [RTSPS] listener opened on :8322 (TCP)
2023/03/25 09:06:03 INF [RTMP] listener opened on :1935
2023/03/25 09:06:03 INF [RTMPS] listener opened on :1936
2023/03/25 09:06:03 INF [HLS] listener opened on :8888
2023/03/25 09:06:03 INF [WebRTC] listener opened on :8889 (HTTP)
free(): invalid pointer
2023/03/25 09:06:03 INF [path cam] [rpicamera source] ERR: process exited unexpectedly
2023/03/25 09:06:05 INF [RTSP] [conn 10.10.10.88:60122] opened
2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [c->s] OPTIONS rtsp://10.10.10.13:8554/cam RTSP/1.0
CSeq: 1
User-Agent: Lavf58.29.100


2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib


2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [c->s] DESCRIBE rtsp://10.10.10.13:8554/cam RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: Lavf58.29.100


2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] non-critical authentication error:
2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 2
Server: gortsplib
WWW-Authenticate: Basic realm="foo"
WWW-Authenticate: Digest realm="foo", nonce="157422fc43aa2410f29d7005eeb13908"


2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [c->s] DESCRIBE rtsp://10.10.10.13:8554/cam RTSP/1.0
Accept: application/sdp
Authorization: Digest username="foo", realm="foo", nonce="157422fc43aa2410f29d7005eeb13908", uri="rtsp://10.10.10.13:8554/cam", response="360b4ff1870c9d40c7c9203419ae1920"
CSeq: 3
User-Agent: Lavf58.29.100


2023/03/25 09:06:05 DEB [RTSP] [conn 10.10.10.88:60122] [s->c] RTSP/1.0 404 Not Found
CSeq: 3
Server: gortsplib


2023/03/25 09:06:05 INF [RTSP] [conn 10.10.10.88:60122] closed (no one is publishing to path 'cam')
free(): invalid pointer
2023/03/25 09:06:08 INF [path cam] [rpicamera source] ERR: process exited unexpectedly
2023/03/25 09:06:10 INF [RTSP] [conn 10.10.10.88:60124] opened
2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [c->s] OPTIONS rtsp://10.10.10.13:8554/cam RTSP/1.0
CSeq: 1
User-Agent: Lavf58.29.100


2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [s->c] RTSP/1.0 200 OK
CSeq: 1
Public: DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, GET_PARAMETER, TEARDOWN
Server: gortsplib


2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [c->s] DESCRIBE rtsp://10.10.10.13:8554/cam RTSP/1.0
Accept: application/sdp
CSeq: 2
User-Agent: Lavf58.29.100


2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] non-critical authentication error:
2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [s->c] RTSP/1.0 401 Unauthorized
CSeq: 2
Server: gortsplib
WWW-Authenticate: Basic realm="foo"
WWW-Authenticate: Digest realm="foo", nonce="1202f1f96e223723028da238681ee30f"


2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [c->s] DESCRIBE rtsp://10.10.10.13:8554/cam RTSP/1.0
Accept: application/sdp
Authorization: Digest username="foo", realm="foo", nonce="1202f1f96e223723028da238681ee30f", uri="rtsp://10.10.10.13:8554/cam", response="fc1332573876eb60f008aebf14078447"
CSeq: 3
User-Agent: Lavf58.29.100


2023/03/25 09:06:10 DEB [RTSP] [conn 10.10.10.88:60124] [s->c] RTSP/1.0 404 Not Found
CSeq: 3
Server: gortsplib


2023/03/25 09:06:10 INF [RTSP] [conn 10.10.10.88:60124] closed (no one is publishing to path 'cam')
free(): invalid pointer
2023/03/25 09:06:13 INF [path cam] [rpicamera source] ERR: process exited unexpectedly
2023/03/25 09:06:15 INF [RTSP] [conn 10.10.10.88:60126] opened
2023/03/25 09:06:15 DEB [RTSP] [conn 10.10.10.88:60126] [c->s] OPTIONS rtsp://10.10.10.13:8554/cam RTSP/1.0
CSeq: 1
User-Agent: Lavf58.29.100

...
```
host 10.10.10.88 is a NVR 

The system that rtsp-simple-server runs on is a Pi 3B+
```
$ apt list | grep -i -e libfreetype -e libcamera0 | grep installed
libcamera0/stable,now 0~git20230302+923f5d70-1 armhf [installed,automatic]
libfreetype-dev/stable,now 2.10.4+dfsg-1+deb11u1 armhf [installed,automatic]
libfreetype6-dev/stable,now 2.10.4+dfsg-1+deb11u1 armhf [installed]
libfreetype6/stable,now 2.10.4+dfsg-1+deb11u1 armhf [installed,automatic]

$ uname -a
Linux rpi3b-1 6.1.19-v7+ #1637 SMP Tue Mar 14 11:04:52 GMT 2023 armv7l GNU/Linux

$ lsb_release --all
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

**Comment by aler9** [comment]
@gofaster can you post your configuration?

**Comment by jarrah31** [comment]
Hi @aler9 
Thank you for implementing this timestamp feature!
I've tested the nightly build and can confirm it works. 🥳 
The only issue that might need looking into is text visibility on a white background as seen in the screenshot below.
image

**Comment by gofaster** [comment]
> @gofaster can you post your configuration?

Here is the full config (stripped out most of the comments).  Above log was with `logLevel: debug`
```
logLevel: info
logDestinations: [stdout]
logFile: /tmp/rtsp-simple-server.log

readTimeout: 10s
writeTimeout: 10s
readBufferCount: 512

externalAuthenticationURL:
api: no
apiAddress: 127.0.0.1:9997

metrics: no
metricsAddress: 127.0.0.1:9998

pprof: no
pprofAddress: 127.0.0.1:9999

runOnConnect:
runOnConnectRestart: no

rtspDisable: no
protocols: [udp, multicast, tcp]
encryption: "optional"
rtspAddress: :8554
rtspsAddress: :8322
rtpAddress: :8000
rtcpAddress: :8001
multicastIPRange: 224.1.0.0/16
multicastRTPPort: 8002
multicastRTCPPort: 8003
serverKey: /etc/ssl/private/x.key
serverCert: /etc/ssl/certs/x.crt
authMethods: [basic, digest]

rtmpDisable: no
rtmpAddress: :1935
rtmpEncryption: "optional"
rtmpsAddress: :1936
rtmpServerKey: /etc/ssl/private/x.key
rtmpServerCert: /etc/ssl/certs/x.crt

hlsDisable: no
hlsAddress: :8888
hlsAlwaysRemux: no
hlsVariant: lowLatency
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsAllowOrigin: '*'
hlsEncryption: yes
hlsServerKey: /etc/ssl/private/x.key
hlsServerCert: /etc/ssl/certs/x.crt
hlsTrustedProxies: []

webrtcDisable: no
webrtcAddress: :8889
webrtcEncryption: no
webrtcServerKey: /etc/ssl/private/x.key
webrtcServerCert: /etc/ssl/certs/x.cer
webrtcAllowOrigin: '*'
webrtcTrustedProxies: []
webrtcICEServers:

paths:
  cam:
    source: rpiCamera
    sourceProtocol: automatic
    sourceAnyPortEnable: no
    sourceFingerprint:

    sourceOnDemand: no
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 10s

    sourceRedirect:
    disablePublisherOverride: no
    fallback:

    rpiCameraCamID: 0
    # width of frames
    rpiCameraWidth: 1640
    # height of frames
    rpiCameraHeight: 1232
    # flip horizontally
    rpiCameraHFlip: true
    # flip vertically
    rpiCameraVFlip: true
    # brightness [-1, 1]
    rpiCameraBrightness: 0.17
    # contrast [0, 16]
    rpiCameraContrast: 1
    # saturation [0, 16]
    rpiCameraSaturation: 1
    # sharpness [0, 16]
    rpiCameraSharpness: 1
    # exposure mode.
    # values: normal, short, long, custom
    rpiCameraExposure: short
    # auto-white-balance mode.
    # values: auto, incandescent, tungsten, fluorescent, indoor, daylight, cloudy, custom
    rpiCameraAWB: auto
    # denoise operating mode.
    # values: auto, off, cdn_off, cdn_fast, cdn_hq
    rpiCameraDenoise: auto
    # fixed shutter speed, in microseconds.
    rpiCameraShutter: 0
    # metering mode of the AEC/AGC algorithm.
    # values: centre, spot, matrix, custom
    rpiCameraMetering: spot
    # fixed gain
    rpiCameraGain: 0
    # EV compensation of the image [-10, 10]
    rpiCameraEV: 0
    # Region of interest, in format x,y,width,height
    rpiCameraROI:
    # tuning file
    rpiCameraTuningFile: /usr/share/libcamera/ipa/raspberrypi/imx219_160.json
    #rpiCameraTuningFile:
    # sensor mode, in format [width]:[height]:[bit-depth]:[packing]
    # bit-depth and packing are optional.
    rpiCameraMode: 3280:2464:10:YUV420
    # frames per second
    rpiCameraFPS: 10
    # period between IDR frames
    rpiCameraIDRPeriod: 10
    # bitrate
    rpiCameraBitrate: 800000
    # H264 profile
    rpiCameraProfile: main
    # H264 level
    rpiCameraLevel: '4.1'
    # Autofocus mode
    # values: auto, manual, continuous
    rpiCameraAfMode: auto
    # Autofocus range
    # values: normal, macro, full
    rpiCameraAfRange: normal
    # Autofocus speed
    # values: normal, fast
    rpiCameraAfSpeed: normal
    # Lens position (for manual autofocus only), will be set to focus to a specific distance
    # calculated by the following formula: d = 1 / value
    # Examples: 0 moves the lens to infinity.
    #           0.5 moves the lens to focus on objects 2m away.
    #           2 moves the lens to focus on objects 50cm away.
    rpiCameraLensPosition: 0.0
    # Specifies the autofocus window, in the form x,y,width,height where the coordinates
    # are given as a proportion of the entire image.
    rpiCameraAfWindow:
    # disables printing text on each frame.
    rpiCameraTextOverlayDisable: false
    # text that is printed on each frame.
    # format is the one of the strftime() function.
    rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - Door'

    # Username required to publish.
    # SHA256-hashed values can be inserted with the "sha256:" prefix.
    publishUser:
    # Password required to publish.
    # SHA256-hashed values can be inserted with the "sha256:" prefix.
    publishPass:
    # IPs or networks (x.x.x.x/24) allowed to publish.
    publishIPs: []

    readUser: <x>
    readPass: <x>
    readIPs: []

    runOnInit:
    runOnInitRestart: no

    runOnDemand:
    runOnDemandRestart: no
    runOnDemandStartTimeout: 10s
    runOnDemandCloseAfter: 10s
    runOnReady:
    runOnReadyRestart: no
    runOnRead:
    runOnReadRestart: no
```

**Comment by aler9** [comment]
@jarrah31 i've added an opaque rectangle below the text, let me know if the text is clearer now.

**Comment by aler9** [comment]
@gofaster i found the issue and uploaded a fix, let me know if it works.

**Comment by jarrah31** [comment]
> @jarrah31 i've added an opaque rectangle below the text, let me know if the text is clearer now.

Thank you @aler9, but sorry to be a pain, could you include a link to a precompiled binary version of the code with the update please? I'm using the armv7 on a Pi4. Thanks.

**Comment by aler9** [comment]
It's in the comment above, i've updated the link

**Comment by gofaster** [comment]
> @gofaster i found the issue and uploaded a fix, let me know if it works.

Yes it's working.  Thanks so much for adding this feature!
image

**Comment by jarrah31** [comment]
> It's in the comment above, i've updated the link

Aha! Thanks for doing that and for implementing the timestamp. I too can confirm it works great now!

**Comment by universe241981** [comment]
Tested with this "rtsp-simple-server_v0.21.6-19-gc8f9a6d_linux_arm64v8.tar.gz"

And it works! 

Screenshot 2023-03-27 112318

**Comment by universe241981** [comment]
Hm...somehow, the stream cannot hold long. The RPi4 1GB halted after couple of minutes and cannot be stream again.

**Comment by mo-g** [comment]
This isn't a functional issue but a "UI" one - it's really weird to me that this is a "Disable" function, or that it's enabled by default. It's not core functionality of a camera stream unless you're doing the specific use case of a Pi CCTV camera, not necessarily appropriate even then, and adds additional processing complexity when using low end devices like a Zero. The default should assume worst case hardware capability. Additionally, if the feature is extended to other sources down the line, then there is no need to have a separate variable for every single possible source type. 

Surely the syntax should be something like:

```
    # Adds a printable text overlay to the top left of the screen
    rpiCameraTextOverlayEnable: false

    # Define the format of the text overlay when using rpiCamera source:
    # (Should follow the syntax of the strftime() function)
    textOverlayFormat: '%Y-%m-%d %H:%M:%S - MediaMTX'

```

Or even:


```
    # Adds a printable text overlay to the top left of the screen.
    # This feature is currently only supported on rpiCamera source!
    textOverlayEnable: false

    # Define the format of the text overlay when using rpiCamera source:
    # (Should follow the syntax of the strftime() function)
    textOverlayFormat: '%Y-%m-%d %H:%M:%S - MediaMTX'

```

**Comment by aler9** [comment]
@mo-g the feature adds a practically-nonexistent processing complexity since it is implemented by hacking frame buffers before they are sent to the hardware encoder, and both components are present even when the camera is used without any overlay.

The feature can't be generalized to other sources since in most other cases it would require decoding and re-encoding the stream, something that this server tries to avoid in any possible way. The only reason why the feature is available on the Raspberry Pi is because the Raspberry Pi doesn't need to decode anything, because it receives raw YUV frames from the camera, and encodes the stream with an hardware component without placing any load on the CPU.

Anyway, you're right about disabling it by default, in order to maintain compatibility with existing configurations.

**Comment by aler9** [comment]
added in v0.22.0

**Comment by mo-g** [comment]
Thanks for changing the syntax, that works better and I understand why you wouldn't generalise further. :)

**Comment by JanPono** [comment]
I love this! Can we have X,Y position parameters of text (or right corners) with different font file? Just to unite with other systems/cameras?

**Comment by aler9** [comment]
@JanPono i intentionally left most customization settings outside the PR in order to encourage the community to contribute them. This is an open source project and settings like text position and font are trivial to implement.

**Comment by Topper69** [comment]
Is it possible to have some dynamic text overlay working like : 
on mediamtx.yml
rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - $CPLOAD'

and export CPLOAD=TEST

Many thanks.

**Comment by aler9** [comment]
@Topper69 you can already do this by renaming the configuration file `mediamtx.yml.in` and using any environment variable inside it:

```yml
paths:
  cam:
    ...
    rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - $CPLOAD'
```

then start the server with

```
export CPLOAD=TEST
cat mediamtx.yml.in | envsubst > mediamtx.yml
./mediamtx
```

**Comment by Topper69** [comment]
@aler9 Thanks. Do you have another solution to change the text overlay on the fly (without overwriting the .yml file and reloading the configuration) ??

**Comment by aler9** [comment]
if you need a dynamic solution you can pull the video stream with a video editing software like OBS and perform all the dynamic updates you want.

**Comment by lchy12345** [comment]
hi, is this for rpi camera only? is it possible to apply to rtsp stream?

**Comment by Topper69** [comment]
> hi, is this for rpi camera only? is it possible to apply to rtsp stream?

Yes this setting si only for rpi camera. If you want to do it for another camera, use a third party app like gstreamer. Look at the readme for more info.

**Pull request merged**
