### PR TITLE
[DEV #1416] Add support for libcamera Autofocus parameters

### PR DESCRIPTION
**Pull request by azsde**
I added most of the parameters as per the official documentation: https://www.raspberrypi.com/documentation/computers/camera_software.html

The only parameter I did not include is the AutoFocus Window, I did not fully understand how it was supposed to work, the documentation specifies a single rectangle but the libcamera defines multiple windows ?

`extern const Control<Span<const Rectangle>> AfWindows;`

### CODE REVIEW

**Comment by azsde** [comment]
@aler9 I fixed the go formatting but I don't know how to trigger the checks again

**Comment by aler9** [comment]
Hello, looks good to me, thanks for the contribution, if you also want to add the afWindows parameter take a look at libcamera-apps:

https://github.com/raspberrypi/libcamera-apps/blob/bce2788644fd25ec1470d18607bb14e1b31b9d23/core/libcamera_app.cpp#L502

window count is fixed to 1. In my opinion libcamera allows multiple windows because it has been designed to be as generic as possible, since its aim is to become the main Linux device API, but that doesn't mean that the RPI Camera supports multiple windows.

**Comment by azsde** [comment]
Alright, I'll probably make another patch tomorrow to support this parameter so that all of the autofocus parameters are supported.

Amazing software by the way, I'm quite amazed by the performance and the ease of use.

**Comment by azsde** [comment]
@aler9 I added the support for autofocus window parameter :)

Feel free to provide some feedback if needed.

**Comment by aler9** [comment]
merged, thank you very much

**Comment by azsde** [comment]
@aler9 you're welcome :-)

**Comment by aler9** [comment]
added in v0.21.3

**Pull request merged**
