### PR TITLE
Add native support for the Raspberry Pi camera

### LINKED ISSUE #1010: Using libcamera-vid
## Describe the feature

Description

I'm trying to inject a raspberry pi camera (h264) stream into FFMPEG from within the `rtsp-simple-server.yaml` file. When running this from outside the container this works as expected, the stream is being forwarded to the rtsp server, and I can SETUP a connection from VLC.

    libcamera-vid -t 0 --inline -o - | ffmpeg -i pipe: -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH

However when trying to run this from within the config, I'm getting a series of `exit code 0`.

    cam:
      runOnInit: libcamera-vid -t 0 --inline -o - | ffmpeg -i pipe: -c copy -f rtsp rtsp://localhost:$RTSP_PORT/$RTSP_PATH
      runOnInitRestart: yes

Any thoughts? I looked at the examples here (https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) but this is no longer applicable I assume (dont work with latest version)

### LINKED ISSUE #1011: Implement native support for the Raspberry Pi Camera
## Describe the feature

The method for using the Raspberry Pi camera with rtspss [described in the README](https://github.com/aler9/rtsp-simple-server#from-a-raspberry-pi-camera) doesn't work anymore due to a Raspberry Pi OS upgrade and the switch to 64 bits arch.

An optimal solution consists into implementing native support for the Raspberry Pi camera directly into server, by interfacing with the native API.

Steps:

1. find a way to interact with dynamic libraries. This is currently impossible since the server is compiled without clib support in order to improve compatibility. We have to find a way to interact with dynamic libraries and at the same time keep compatibility as broader as possible. Maybe the server can be released with two executables, one for generic aarch 64, and the other for the Raspberry Pi OS aarch 64.

2. interact with camera APIs / [MMAL interface](https://github.com/raspberrypi/userland/blob/master/interface/mmal/mmal.h) in order to extract H264 and make it available.

### PR DESCRIPTION
**Pull request by aler9**
Fixes #1011

Fixes #1010

### CODE REVIEW

**Comment by cedricve** [comment]
@aler9 any idea when this will be made available on Docker hub?

**Comment by aler9** [comment]
@cedricve the Docker version doesn't support the RPI camera natively, but the standard version does. Just take a look at the README in order to try the feature.

**Comment by cedricve** [comment]
ok thank you just wondering what this PR fixes then? Is it just support for libcamera (but outside a docker container)?

Kind regards,
Verstraeten Cédric

**Comment by aler9** [comment]
This PR allows the serve to interact with libcamera natively, skipping all the Gstreamer stack. GStreamer is not needed anymore.

The Docker version may come in the future, but I have to check whether the camera can be accessed from a container.

**Comment by cedricve** [comment]
it does, is you inject the devices or make it previleged. 

Kind regards,
Verstraeten Cédric

**Comment by olokos** [comment]
Looks awesome, good job!

https://github.com/aler9/rtsp-simple-server/pull/1057/files#diff-fc943529e712158406c15ccb0d56f2afcd02a8d98a193c7623885e3d33366abdR4

I was wondering about those parameters, are there plans to support all of the native parameters with 1:1 names?
There's around 40 parameters or more for `libcamera-vid --help`

I was thinking, maybe instead of hardcoding parameters for libcamera-vid, some kind of wrapper approach could be used instead?

Right now it seems like most of true native Raspberry Pi Camera features/parameters are in fact unavailable, to some degree, but I might be completely wrong. :)


IIRC the bitrate is VBR by default for libcamera

**Comment by olokos** [comment]
In terms of accessing host device from within docker container, that is possible!
https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device

**Comment by aler9** [comment]
I opened two enhancement request in order to track the two features requested by @cedricve and @olokos :

#1110 Allow to use the Raspberry Camera with Docker

#1111 Allow to set additional parameters of the Raspberry Pi Camera

Discussion will be moved there.

**Pull request merged**
