### PR TITLE
m3u8 relative url fixed (starting with // and with query string)

### PR DESCRIPTION
**Pull request by vgavro**
Urls starting with // and urls with query string parsed improperly, this pull request fixes this.

### CODE REVIEW

**Comment by vgavro** [comment]
Looks like https://pkg.go.dev/net/url#URL.ResolveReference is better way to do this. I'll test it and change implementation in near future.

**Comment by vgavro** [comment]
> Looks like https://pkg.go.dev/net/url#URL.ResolveReference is better way to do this. I'll test it and change implementation in near future.

done

**Comment by aler9** [comment]
Hello, thanks for this contribution, using `ResolveReference()` is an elegant way to solve all relative paths-related issues.

Before merging, can you post the content of a `.m3u8` playlist that contains relative URLs that couldn't be parsed before this patch? i need to add them to unit tests. Thanks

**Comment by vgavro** [comment]
> Before merging, can you post the content of a `.m3u8` playlist that contains relative URLs that couldn't be parsed before this patch? i need to add it to unit tests. Thanks

Examples:
http://live.ren.tv/ren/stream1/playlist.m3u8
http://live.ren.cdnvideo.ru/ren/stream1/chunklist.m3u8

NOTE: cdnvideo.com (also cdnvideo.ru) is pretty popular in post-USSR countries service for online publishing, which is now blocked for ukrainian IPs because of war, before that there were some ukrainian tv-channels (now deleted by service).
P.S. (not relevant) Thanks for supporting Ukraine!

**Comment by aler9** [comment]
I merged the fix and made sure the stream you provided is compatible with the server. HLS is implemented in multiple ways and there aren't many publicly-available sources, so it's really easy to encounter bugs. 

In my town the Ukranian flag is raised above the city hall, we're preparing to welcome and host refugees, and we've already sent a couple of trucks to the country:
https://www-mbnews-it.translate.goog/2022/03/manifestazioni-per-la-pace-in-centinaia-i-brianzoli-in-piazza-ecco-le-prossime-date/?_x_tr_sl=it&_x_tr_tl=en&_x_tr_hl=it&_x_tr_pto=wapp

**Pull request merged**
