### PR TITLE
added new metric

### PR DESCRIPTION
**Pull request by naman108**
this branch has added a new metric allowing for the user to view the current paths being published to

### CODE REVIEW

**Comment by naman108** [comment]
this pull is for v0.16.1 because we weren't able to support multiple publishers on higher versions and even here we have some issue. This pull was created to support the FreeTAKServer project for drone streams and mobile phone streams. any help would be greatly appreciated in terms of addressing the issues with multiple publishers.

**Comment by shalomcrown** [comment]
I am also interested in this change, I need per-publisher incoming byte counts.

**Comment by aler9** [comment]
Hello, thanks for the contribution, i'm waiting to merge this since i'm working on an HTTP API that provides the same feature. If there is any problem during the development, this will get merged.

**Comment by aler9** [comment]
A PR to implement an HTTP API is finally available here #483 - the API provides a list of all paths, publishers and readers, therefore it fully covers the features proposed by this PR.

**Comment by aler9** [comment]
an HTTP API is available in v0.17.0

**Comment by naman108** [comment]
great thank you!

**Pull request closed without merging**
