### PR TITLE
support reading H265 tracks with HLS

### LINKED ISSUE #469: Add HLS support for h265 rtsp.
## Describe the feature

Description
The Server support HLS for h264 rtsp but when I tried using h265 rtsp it is unable to create .m3u8 file. I think for HLS it doesn't have h265 decoder.

please add HLS support for h265 rtsp.

### PR DESCRIPTION
**Pull request by aler9**
Fixes #469

### CODE REVIEW

**Comment by thanhlnbka** [comment]
I tried pushlish rtsp format h265 to the server and read with hls low latency but it didn't work
I got an error like this, do you know why ? 
image

**Comment by aler9** [comment]
@thanhlnbka can you provide a sample video that triggers the error? Thanks

**Comment by thanhlnbka** [comment]
Sorry, I can't give you a sample video because I use h265 rtsp stream to pushlish to the server. 
i use ffmpeg to push :  ffmpeg  -i rtsp:// -c copy -f rtsp rtsp://localhost:8554/mystream and open vlc with stream rtsp://localhost:8554/mystream as well

**Comment by aler9** [comment]
You can generate a sample by running

```
ffmpeg -i rtsp://yourcamera -t 00:30:00 -c copy -f mpegts mysample.ts
```

**Pull request merged**
